import Head from 'next/head'
import { TheEditor } from '../components/TheEditor'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className='text-5xl pb-64'>SlateJS + Next Demo</h1>
        <div className='w-full lg:w-1/2'><TheEditor/></div>
      </main>
    </div>
  )
}
